PREFIX dbp: <http://dbpedia.org/property/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dboPlanet: <http://dbpedia.org/ontology/Planet/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ling: <http://purl.org/linguistics/gold/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# SELECT DISTINCT * WHERE {
#     ?planet rdf:type dbo:Planet;
#         rdfs:label ?planetName;
#         # dbp:angularSize ?planetAngularSize;
#         # dbp:meanRadius ?planetRadius;
#         # dbo:meanTemperature ?planetTemp.
#         dbo:volume ?planetVolume.
        
#         # dboPlanet:averageSpeed ?planetSpeed.
#     FILTER(LANGMATCHES(LANG(?planetName), "EN") 
#         && (ABS(?planetVolume - 57.74)/57.74) < 0.5).
# }
SELECT ?planetName 
?planetVolume 
?planetSpeed 
(AVG(?planetTemp) as ?temp) WHERE {
        ?planet rdf:type dbo:Planet;
        rdfs:label ?planetName.
        ?planet dbo:volume ?planetVolume.
        ?planet dbo:meanTemperature ?planetTemp.
        ?planet dboPlanet:averageSpeed ?planetSpeed.
        FILTER(LANGMATCHES(LANG(?planetName), "EN") 
        && (ABS(?planetVolume - 57.74)/57.74) < 0.9
        && (ABS(?planetTemp - 55)/55) < 0.9 
        && (ABS(xsd:double(?planetSpeed) - 5.43)/5.43) < 0.5
        ).
        }
# GROUP BY ?planetName ?planetVolume ?planetSpeed

# SELECT DISTINCT (count(?planet) as ?planetCount) WHERE {
#     ?planet rdf:type dbo:Planet;
#         rdfs:label ?planetName;
#         # dbp:angularSize ?planetAngularSize;
#         # dbp:meanRadius ?planetRadius;
#         # dboPlanet:volume ?planetVolume.
#         dbo:volume ?planetVolume.
#         # dboPlanet:averageSpeed ?planetSpeed.
#         # dbo:meanTemperature ?planetTemp
#     FILTER(LANGMATCHES(LANG(?planetName), "EN"))
# }


